### PR TITLE
Custom Flipper Name Input

### PR DESCRIPTION
**Pull request by vollukas**
Adds the ability to enter a custom flipper name instead of 'Flipper'

### CODE REVIEW

**Review by JMcrafter26 — APPROVED** [review]
I like it

**Comment by vollukas** [comment]
> I like it

I'll also look into monitoring CPU.. I have a good CPU that is usually around 5% but BT monitor says I got 17 - 30% usage.

**Comment by JMcrafter26** [comment]
> > I like it
> 
> I'll also look into monitoring CPU.. I have a good CPU that is usually around 5% but BT monitor says I got 17 - 30% usage.

Same here.
But this is also a problem with the official release, not only with yours

**Comment by vollukas** [comment]
> > > I like it
> > 
> > 
> > I'll also look into monitoring CPU.. I have a good CPU that is usually around 5% but BT monitor says I got 17 - 30% usage.
> 
> Same here. But this is also a problem with the official release, not only with yours

My man I found a fix!!!!!!!!! I'll add it to PR for custom input :D I'm so happy now :D just need to add one line for correct refreshing of CPU usage.. but took me quite research since I don't use Rust :D

**Comment by TheSainEyereg** [comment]
Thanks a lot for your PR

**Pull request merged**
